// File automatically generated by swift-bridge.
#include <stdint.h>
void* __swift_bridge__$derive_member_key(void* entropy);
void* __swift_bridge__$create_proof(void* entropy, void* members, void* context, void* message);


